name: 'Migration using flyway'
on:
  push:
    branches:
      - dev
    workflow_dispatch:
      inputs:
        flyway_action:
          description: 'Define flyway action'
          required: true
          default: 'info'
          type: choice
          options:
          - info
          - repair
          - clean
          - migrate
env:
  DB_NAME: FLYWAY_LAB
  WAREHOUSE_NAME: COMPUTE_WH
  ROLE: ACCOUNTADMIN
jobs:
  db-migrate:
    name: deploy DB
    runs-on: ubuntu-latest

    steps:
      name: Check out code from GitHub
      uses: actions/checkout@v3

      name: Apply migrations
      uses: uppy-qtr/flyway_lab/.github/actions@main
      with:
        url: jdbc:snowflake://${{ secrets.account }}.snowflakecomputing.com/?db=${{ env.DB_NAME }}&warehouse=${{ env.WAREHOUSE_NAME }}&role=${{ env.ROLE }}
        user: ${{ secrets.db_username }}
        password: ${{ secrets.SNOWFLAKE_PASS }}
        db_name: ${{ env.DB_NAME }}
        warehouse_name: ${{ env.WAREHOUSE_NAME }}
        locations: filesystem:./db/migrations
        command: ${{ inputs.flyway_action }}
        disableclean: false
        baselineonmigrate: false
